/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MANH TRUONG
 */
public class menuQuanlynhansu extends javax.swing.JFrame {

    /**
     * Creates new form menuQuanlynhansu
     */
    public menuQuanlynhansu() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    private void ButtonClose(String title) {
        int index = jTabbedPane1.indexOfTab(title);
        JPanel pnlTab = new JPanel(new GridBagLayout());
        pnlTab.setOpaque(false);
        JLabel lblTitle = new JLabel(title);
        JButton btnClose = new JButton("x");

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1;

        pnlTab.add(lblTitle, gbc);

        gbc.gridx++;
        gbc.weightx = 0;

        pnlTab.add(btnClose, gbc);

        jTabbedPane1.setTabComponentAt(index, pnlTab);
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Component selected = jTabbedPane1.getSelectedComponent();
                if (selected != null) {
                    jTabbedPane1.remove(selected);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnChucVu = new javax.swing.JButton();
        btnChuyenMon = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnPhongBan = new javax.swing.JButton();
        btnTrinhDoHocVan = new javax.swing.JButton();
        btnLuong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        btnChucVu.setBackground(new java.awt.Color(0, 0, 255));
        btnChucVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChucVu.setForeground(new java.awt.Color(255, 255, 51));
        btnChucVu.setText("Quản lý chức vụ ");
        btnChucVu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucVuActionPerformed(evt);
            }
        });

        btnChuyenMon.setBackground(new java.awt.Color(0, 0, 255));
        btnChuyenMon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChuyenMon.setForeground(new java.awt.Color(255, 255, 51));
        btnChuyenMon.setText("Quản lý chuyên môn ");
        btnChuyenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenMonActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(0, 0, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 51));
        btnNhanVien.setText("Quản lý nhân viên ");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnPhongBan.setBackground(new java.awt.Color(0, 0, 255));
        btnPhongBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPhongBan.setForeground(new java.awt.Color(255, 255, 51));
        btnPhongBan.setText("Quản lý phòng ban ");
        btnPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongBanActionPerformed(evt);
            }
        });

        btnTrinhDoHocVan.setBackground(new java.awt.Color(0, 0, 255));
        btnTrinhDoHocVan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTrinhDoHocVan.setForeground(new java.awt.Color(255, 255, 51));
        btnTrinhDoHocVan.setText("Quản lý trình độ học vấn ");
        btnTrinhDoHocVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrinhDoHocVanActionPerformed(evt);
            }
        });

        btnLuong.setBackground(new java.awt.Color(0, 0, 255));
        btnLuong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLuong.setForeground(new java.awt.Color(255, 255, 51));
        btnLuong.setText("Quản lý lương");
        btnLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrinhDoHocVan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(btnChuyenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(47, 47, 47)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnPhongBan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(btnTrinhDoHocVan, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenMonActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý chuyên môn") <= -1) {
            jTabbedPane1.add("Quản lý chuyên môn", new ChuyenMon());
            ButtonClose("Quản lý chuyên môn");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý chuyên môn"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý chuyên môn"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnChuyenMonActionPerformed

    private void btnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucVuActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý chức vụ") <= -1) {
            jTabbedPane1.add("Quản lý chức vụ", new ChucVu());
            ButtonClose("Quản lý chức vụ");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý chức vụ"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý chức vụ"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnChucVuActionPerformed

    private void btnLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý lương") <= -1) {
            jTabbedPane1.add("Quản lý lương", new Luong());
            ButtonClose("Quản lý lương");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý lương"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý lương"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnLuongActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý nhân viên") <= -1) {
            jTabbedPane1.add("Quản lý nhân viên", new NhanVien());
            ButtonClose("Quản lý nhân viên");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý nhân viên"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý nhân viên"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongBanActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý phòng ban") <= -1) {
            jTabbedPane1.add("Quản lý phòng ban", new PhongBan());
            ButtonClose("Quản lý phòng ban");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý phòng ban"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý phòng ban"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnPhongBanActionPerformed

    private void btnTrinhDoHocVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrinhDoHocVanActionPerformed
        if (jTabbedPane1.indexOfTab("Quản lý trình độ học vấn") <= -1) {
            jTabbedPane1.add("Quản lý trình độ học vấn", new TrinhDoHocVan());
            ButtonClose("Quản lý trình độ học vấn");
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý trình độ học vấn"));
        } else {
            jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Quản lý trình độ học vấn"));
            JOptionPane.showMessageDialog(this, "Mục này đang được mở ");
        }
    }//GEN-LAST:event_btnTrinhDoHocVanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuQuanlynhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuQuanlynhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuQuanlynhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuQuanlynhansu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuQuanlynhansu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnChuyenMon;
    private javax.swing.JButton btnLuong;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhongBan;
    private javax.swing.JButton btnTrinhDoHocVan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
